- name: Install Vagrant and Python3.5 from SCL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - rh-python35
    - sclo-vagrant1

- name: Check Vagrant
  shell: '{{ vagrant_scl_exec }} vagrant --version'
  become: true

- name: Install Packages
  yum: 
    name: '{{ item }}' 
    state: present
  become: true
  with_items:
    - libvirt
    - git
    - gcc
    - libffi-devel
    - openssl-devel
    - patch

- name: Install Pipsi
  shell: '{{ python3_scl_exec }} pip3.5 install pipsi'
  become: true

- name: Install Pew
  shell: '{{ python3_scl_exec }} pipsi --bin-dir=/usr/bin install pew'
  become: true

- name: Install Pipenv
  shell: '{{ python3_scl_exec }} pipsi --bin-dir=/usr/bin install pipenv'
  become: true

- name: Checkout `le-app-to` code
  git:
    repo: https://github.com/leapp-to/prototype/
    dest: /srv/le-app
  become: true

- name: Prepare `pipenv`
  shell: '{{ python3_scl_exec }} pipenv --three'
  args:
    chdir: /srv/le-app
  become: true

- name: Install `pipenv`
  shell: '{{ python3_scl_exec }} pipenv install --dev --ignore-hashes'
  args:
    chdir: /srv/le-app
  become: true
